### ISSUE TITLE
vim Wrong font background

### ISSUE THREAD

**Issue by q107580018** [dracula/vim#175] opened 2020-03-31 08:39 UTC
When I use vim，It shows abnormally:
![Xnip2020-03-31_16-36-26](https://user-images.githubusercontent.com/44695873/78005231-d7f4de00-736d-11ea-8694-10770b1c0c0f.jpg)
When I use neovim，It is ok:
![Xnip2020-03-31_16-37-43](https://user-images.githubusercontent.com/44695873/78005303-f3f87f80-736d-11ea-893e-6111fc86ef73.jpg)

 I don't know why?
vim and neovim are use the same vimrc
Vim version:8.2
NeoVim version:0.4.3
my env:
![Xnip2020-03-31_17-04-24](https://user-images.githubusercontent.com/44695873/78008057-bbf33b80-7371-11ea-853c-931600cb5ae7.jpg)

**Comment by dsifford** [comment] 2020-03-31 12:37
Dupe of #114, #115, #127, #166 

Set `let g:dracula_italic = 0` in your vimrc prior to setting the colorscheme. Your terminal doesn't support italic fonts in the font you have selected.

**Closed by dsifford** 2020-03-31 12:37 UTC
