### ISSUE TITLE
Using this color scheme set my vim to grayscale

### ISSUE THREAD

**Issue by eric-smithson** [dracula/vim#57] opened 2018-02-20 15:14 UTC
I installed by copying dracula.vim into my /.vim/color folder.

After running `:colo dracula` my vim was set to grayscale. 

Not sure what's going on here, the only other plugin I have that I could see interfering with this color scheme is vim-go.

**Comment by satore11** [comment] 2018-03-14 09:05
Same Issue... installed wiht vundle.

**Comment by dsifford** [comment] 2018-03-20 00:14
@eric-smithson When you say "your vim was set to grayscale", what exactly do you mean by that?

Screenshot?

(Just joining this repo as a maintainer today, so trying to catch myself up)

Thanks

**Comment by dsifford** [comment] 2018-03-20 00:14
Is this a dupe of #51 ?

**Comment by eric-smithson** [comment] 2018-03-20 13:29
@dsifford Yeah it's a dupe of #51.

**Closed** 2018-03-20 15:51 UTC
