### ISSUE TITLE
[neovim] Background color not displaying in neovim

### ISSUE THREAD

**Issue by patrl** [dracula/vim#11] opened 2016-08-19 14:36 UTC
When using the dracula theme in neovim, the terminal background color appears to override the theme background color. This is illustrated below, with urxvt on the left and st on the right, showing that this issue is independent of the terminal emulator used.

![dracula-nvim](https://cloud.githubusercontent.com/assets/13229321/17813231/65c12e26-6622-11e6-9d5a-55a802381151.png)

Here is my init.vim (note that I used vim-plug to install the dracula theme):

```
call plug#begin()
        Plug 'dracula/vim'
        Plug 'vim-airline/vim-airline'
call plug#end()

colorscheme dracula
```

**Comment by idlua** [comment] 2016-11-01 23:49
I believe this to be solved it with this #19.

**Comment by dukebarman** [comment] 2017-06-15 12:58
@patrl, try to add `set termguicolors` in `~/.config/nvim/init.vim`

It works for me in iTerm2

**Comment by NikhilMTomy** [comment] 2017-07-05 16:16
I also have this problem on xterm. But the neovim background is not that of the terminal either.

**Comment by Drowze** [comment] 2018-03-20 01:35
Can confirm 
![image](https://user-images.githubusercontent.com/9031589/37630714-de63beb6-2bc4-11e8-864a-15b67b537ba2.png)

(plus, setting termguicolors simply messes with the colors...)
Tested on gnome-terminal, urxvt, terminator
Ubuntu 16.04
NVIM v0.2.2
Dracula v1.2.7
Plus I am using plug-vim.

**Comment by dsifford** [comment] 2018-03-20 16:32
@dukebarman Is correct. Issue boils down to the `termguicolors` option not pairing well with how we currently are setting highlights.

I'll be working on a more hardened fix for this over the next several days as time allows.

**Comment by benknoble** [comment] 2018-03-28 09:29
Related to #59 perhaps ?

**Comment by dsifford** [comment] 2018-03-28 20:50
Should be fixed now. Let me know otherwise.

**Closed by dsifford** 2018-03-28 20:50 UTC
Labels: bug

**Comment by loganbickmore** [comment] 2018-04-25 01:43
Issue still exists for me using urxvt.

**Comment by dsifford** [comment] 2018-04-25 01:51
@loganbickmore Do you have `set termguicolors` enabled?

**Comment by loganbickmore** [comment] 2018-04-25 05:40
@dsifford With `set termguicolors` enabled I the screen lights up green.  Without it enabled it appears like the original issues screenshot.

**Comment by dsifford** [comment] 2018-04-25 08:11
@loganbickmore see https://github.com/dracula/vim/issues/60

@pdaniell were you ever able to figure out what caused that green color?

**Comment by benknoble** [comment] 2018-04-25 17:42
I'm convinced the 'green screen' effect is caused by setting `termguicolors` in a term (like macOS Terminal) that doesn't support truecolor.

**Comment by benknoble** [comment] 2018-04-25 17:46
Could also be related to the `dracula_colorterm` variable as laid out in the help file and over at #65

**Comment by loganbickmore** [comment] 2018-04-25 21:38
@dsifford `g:dracula_colorterm = 0` resolved the issue. Thank you for you're help, sorry to start adding comments after the issue was closed.

**Comment by dsifford** [comment] 2018-04-25 22:32
@loganbickmore No worries. Glad we could get it sorted out :+1:
