### ISSUE TITLE
Listchars has the wrong background color

### ISSUE THREAD

**Issue by abbec** [dracula/vim#44] opened 2017-09-05 11:50 UTC
Like this

![screen shot 2017-09-05 at 13 49 31](https://user-images.githubusercontent.com/455022/30059824-0f4cb74e-9241-11e7-9511-f46edcea1cc4.png)

I would expect both the dots and tab markers to have the standard background color.

**Comment by steven-joruk** [comment] 2017-12-16 22:07
This can be fixed by setting `ctermbg=NONE` for `SpecialKeys`.

**Comment by abbec** [comment] 2017-12-20 13:22
Yeah, I did these customizations to make it nicer in a terminal:

```viml
hi SpecialKey cterm=NONE ctermfg=darkgray ctermbg=NONE
hi NonText ctermfg=darkgray
hi VertSplit ctermfg=darkgray ctermbg=NONE

hi ALEError cterm=underline ctermfg=red
hi ALEErrorSign cterm=underline ctermfg=red
hi ALEWarning cterm=underline ctermfg=yellow
hi ALEWarningSign cterm=underline ctermfg=yellow
```

**Comment by zenorocha** [comment] 2018-02-16 09:35
Should we add this to the theme @BlakeWilliams?

**Comment by dsifford** [comment] 2018-03-20 00:10
@abbec @steven-joruk Can I assume that both of you are/were using a terminal that has a different color background than the primary dracula background color?

I can't reproduce this.

**Comment by abbec** [comment] 2018-03-21 12:26
I am using dracula in my terminal as well (iterm2).

**Comment by dsifford** [comment] 2018-03-21 14:08
@abbec I was able to target the issue locally last night. 

Are you by chance running tmux or gnu screen?

**Comment by abbec** [comment] 2018-03-21 14:56
I am not running tmux or screen and my vim version is:

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar  2 2018 02:50:34)
macOS version
Included patches: 1-1553
Compiled by Homebrew
```

**Comment by dsifford** [comment] 2018-03-21 15:03
Ah, shoot... I would have had it for sure if you were running tmux.

Do you have `set termguicolors` enabled?

**Comment by abbec** [comment] 2018-03-21 15:07
Nope :)

**Comment by dsifford** [comment] 2018-03-21 15:11
Did that work?

**Comment by dsifford** [comment] 2018-03-21 16:13
The GUI colors are what you'd _want_ to use, no?

Otherwise you're limited to a set of, at most, 256 colors.

**Comment by abbec** [comment] 2018-03-21 16:15
Sure, but I (and maybe others) would also want it to look ok in a terminal that does not have true color support.

**Closed** 2018-03-21 16:39 UTC
