### ISSUE TITLE
MacOS variable types highlighted C

### ISSUE THREAD

**Issue by matty0005** [dracula/vim#206] opened 2020-08-08 08:33 UTC
### What happened
Variable types are highlighted/inverted on MacOS (10.15.5) terminal in vim (version: 8.1).
 I have added the "let g:dracula_italic = 0" to my vimrc file, but didn't change anything

My friend also has the same issue. 

### Screenshot
![Screen Shot 2020-08-08 at 5 08 58 pm](https://user-images.githubusercontent.com/24428467/89705954-ef3f7a00-d9a4-11ea-81ec-ae89670aaf11.png)
Here's a screenshot of my .vimrc file
![Screen Shot 2020-08-08 at 5 08 34 pm](https://user-images.githubusercontent.com/24428467/89705963-03837700-d9a5-11ea-9cb0-b4213db93b09.png)

**Comment by dsifford** [comment] 2020-08-08 14:18
Dupe of #114, #115, #127, #166, #175, #189 

Set `let g:dracula_italic = 0` in your vimrc prior to setting the colorscheme. Your terminal doesn't support italic fonts in the font you have selected.

**Closed by dsifford** 2020-08-08 14:18 UTC
