### ISSUE TITLE
[Feature Request]: lsp semantic highlight

### ISSUE THREAD

**Issue by I-Want-ToBelieve** [dracula/vim#290] opened 2022-09-21 03:35 UTC
https://github.com/dracula/vim/issues/271

### Machine Info

- **Vim type (`vim`/`gvim`/`neovim`)**: neovim
- **Vim version**:0.7.2
- **OS**: archlinux
- **Terminal/Terminal Emulator/VTE**: kitty
- **`TERM` environment variable**: xterm-kitty

### Additional Info

https://github.com/theHamsta/nvim-semantic-tokens

**Comment by benknoble** [comment] 2022-09-21 13:54
What exactly is the request here?

- We have some Treesitter support
- #271 is closed with possible ways for users to resolve the discrepancy
- the 'Additional Info' link doesn't explain the request

**Comment by backtolife2021** [comment] 2022-09-22 05:14
Using LSP's semantic highlighting as a complement to Treesitter highlighting eliminates differences with Vscode highlighting

When neovim is ready to provide lsp semantic tokens, the only thing the theme plugin needs to do is map LSP highlight groups  to colors or highlight groups you like to actually see semantic highlights.

**Comment by benknoble** [comment] 2022-09-22 12:17
Is that somehow different from https://github.com/dracula/vim/blob/master/colors/dracula.vim#L263-L275 ?

Is this something for which we need to monitor NeoVim releases to know when this feature stabilizes?

**Comment by benknoble** [comment] 2022-09-22 12:18
(I think the answer to my first question is yes.)

**Comment by backtolife2021** [comment] 2022-09-23 05:32
> (I think the answer to my first question is yes.)

You are right, I quoted the previous question to illustrate what can be done next

**Comment by backtolife2021** [comment] 2022-09-23 05:52
https://github.com/dracula/vim/blob/master/colors/dracula.vim#L263-L275 defines some mappings for LSP diagnostic highlight groups

The lsp semantic highlighting group is about the highlighting group of syntax tokens with different semantics
For example a variable variable and a read-only constant variable can have different LSP highlight groups: LspVariable and LspVariableReadOnly. Thanks to this, we can map them with different colors.

**Comment by backtolife2021** [comment] 2022-09-24 09:18
> Is this something for which we need to monitor NeoVim releases to know when this feature stabilizes?

Now there is a neovim plugin that implements LSP semantic highlighting, which can be used but may not be merged into nvim-treesitter for a while

**Comment by backtolife2021** [comment] 2022-09-24 09:31
I tried this plugin, and the effect is very good. It can be said that it is very close to the rendering effect of vscode, except for a few small flaws caused by the completely different syntax highlighting mechanism of treesitter and textmate

![image](https://user-images.githubusercontent.com/24669431/192090420-14a391ac-2d69-488b-8363-05aeb55d325c.png)

![image](https://user-images.githubusercontent.com/24669431/192090841-e9a18e3a-cfec-407c-b46b-42aa311e69ab.png)

![image](https://user-images.githubusercontent.com/24669431/192090938-701c7788-42fd-41d8-9d94-943b493d5c71.png)

**Comment by benknoble** [comment] 2022-09-26 14:11
I don't know what you mean by "customizing highlights.scm."

My major concern is that this appears to be an experimental plugin and not NeoVim core—I would be more comfortable waiting until the features land in NeoVim core.

What do you think @dsifford? I don't use NeoVim, so I don't know if my understanding of the situation is correct or not.

**Comment by dsifford** [comment] 2022-09-26 14:14
I think it's fine to accept PRs for this so long as it's wrapped in a `has()` condition (like other plugins we support)..

But for very specific customizations, I think it would be safer to customize down to the language level and not broadly...

So, for example.. Instead of `@constructor.imported`, maybe do `@constructor.imported.javascript`

**Comment by backtolife2021** [comment] 2022-09-27 05:35
customizing highlights.scm refers to https://github.com/nvim-treesitter/nvim-treesitter#adding-queries

**Comment by backtolife2021** [comment] 2022-09-27 05:42
Given that this experimental plugin [seems to be different from the LSP semantic highlighting specification](https://github.com/theHamsta/nvim-semantic-tokens/issues/20), I can submit a PR about the LSP semantic highlighting group mapping after the plugin's author has dealt with it, and about the custom highlights.scm section, There is no definite specification, just record it here for the time being.

**Comment by tobealive** [comment] 2023-02-05 12:29
Since semantic tokens support was merged (https://github.com/neovim/neovim/pull/21100) dracula themes highlights break when the client attaches. 

A 5 sec example using nvim nighlty, dracula and sumenko-lua as lsp:
https://user-images.githubusercontent.com/34311583/216818502-6619c4bd-9f9e-4407-8a28-a674115de84c.mp4

For now the way I found to go about is to `nil` the `semanticTokensProvider` when dracula is used or call `vim.lsp.semantic_tokens.stop()` for language server or to manually extend the highlight groups like @I-Want-ToBelieve  describes above.

As it becomes harder to write good code without a dracula theme 🧛🏻‍♂️,
do you have the chance to extend the themes highlighting to that @dsifford, @benknoble? 😊

**Comment by benknoble** [comment] 2023-02-05 13:28
As I have said before, contributions are welcome in the form of PRs. This isn't something I use or even would be in a position to test (except that it doesn't break plain old Dracula on Vim).

Last I heard Derek was pretty busy, though he might be in a better position with respect to this feature now.

**Comment by xiantang** [comment] 2023-07-30 04:24
try https://github.com/xiantang/darcula-dark.nvim

**Closed** 2023-10-29 13:48 UTC
