### ISSUE TITLE
Unexpected background colour in Neovim in Terminal.app on macOS Big Sur 11.2.3

### ISSUE THREAD

**Issue by owzXEi** [dracula/vim#238] opened 2021-04-05 20:48 UTC
### What happened
Background colour appears as `#303030`
### What I expected to happen
Background colour to appear as `#282a36`
### Screenshot
![Screenshot 2021-04-05 at 21 23 42](https://user-images.githubusercontent.com/79711472/113624462-97523380-9657-11eb-80aa-1f9db3b20f4b.png)
### Machine Info
- **Vim type (`vim`/`gvim`/`neovim`)**:
neovim
- **Vim version**:
NVIM v0.4.4 (Compiled by brew@BigSur)
- **OS**:
macOS Big Sur Version 11.2.3
- **Terminal/Terminal Emulator/VTE**:
Terminal.app
- **`TERM` environment variable**:
xterm-256color
### Additional Info
Adding `set guitermcolors` results in:
![Screenshot 2021-04-05 at 21 28 55](https://user-images.githubusercontent.com/79711472/113624880-18112f80-9658-11eb-9288-3e368231c643.png)

**Comment by dsifford** [comment] 2021-04-05 22:42
Dupe of #117, #164, #176, and a few others. 

Check those threads and you should find your answer.

**Closed by dsifford** 2021-04-05 22:42 UTC

**Comment by owzXEi** [comment] 2021-04-06 08:05
> Dupe of #117, #164, #176, and a few others.
> 
> Check those threads and you should find your answer.

Apologies - thanks for your pointing me in the right direction @dsifford.
