### ISSUE TITLE
theme fill background color for primitive types(int,bool,string)

### ISSUE THREAD

**Issue by renatosuero** [dracula/vim#189] opened 2020-05-14 18:55 UTC
### What happened
When I add a variable bool,string,int I have a background color in the name
### What I expected to happen
 I'd like to remove that
### Screenshot
![Screenshot 2020-05-14 at 20 47 51](https://user-images.githubusercontent.com/1093214/81973755-e0a32a00-9624-11ea-934a-a340a4225684.png)

### Machine Info
Darwin renatos-mbp.home 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
- **Vim type (`vim`/`gvim`/`neovim`)**: Vim
- **Vim version**: 8.2.539
- **OS**: OSX
- **Terminal/Terminal Emulator/VTE**: alacrity/iterm
- **`TERM` environment variable**: screen-256color

**Comment by dsifford** [comment] 2020-05-14 18:59
Dupe of #114, #115, #127, #166, #175

Set let g:dracula_italic = 0 in your vimrc prior to setting the colorscheme. Your terminal doesn't support italic fonts in the font you have selected.

**Closed by dsifford** 2020-05-14 18:59 UTC
